name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Run tests
    #   run: dotnet test --no-restore --no-build --verbosity normal
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.2.0
      with:
        versionSpec: '5.x'
    - name: Display GitVersion config
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.2.0
    - name: Publish
      run: dotnet pack --no-restore /p:AssemblyVersion=${{ steps.gitversion.outputs.GitVersion_AssemblySemVer }} /p:Version=${{ steps.gitversion.outputs.GitVersion_FullSemVer }}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        path: '**/*.nupkg'
