name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Run tests
    #   run: dotnet test --no-restore --no-build --verbosity normal
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.2.0
      with:
        versionSpec: '5.x'
    - name: Display GitVersion config
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.2.0
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v5
      id: changelog
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: "false"
        skip-git-pull: "true"
        skip-version-file: "true"
        skip-commit: "true"
        skip-tag: "true"
    - name: Pack
      run: dotnet pack --no-restore /p:AssemblyVersion=${{ steps.gitversion.outputs.GitVersion_AssemblySemVer }} /p:Version=${{ steps.gitversion.outputs.GitVersion_FullSemVer }}
    - name: Push Package to GitHub
      run: dotnet nuget push --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} **/*.nupkg
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}
        release_name: ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}
        body: |
          ${{ steps.changelog.outputs.clean_changelog }}
